

name: 'Fibonacci Comment On PR'
description: 'Posts a comment on a PR with the Fibonacci of numerical values in the diff.'
inputs:
  max_threshold:
    description: 'The maximum numerical value for which Fibonacci will be computed.'
    required: true
    type: number
  enable_fib:
    description: 'Whether to enable posting the Fibonacci comment (true/false).'
    required: true
    type: boolean
runs:
  using: 'composite'
  steps:
    - run: |
        cargo run
      env:
        TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.number }}
        INPUT_MAX_THRESHOLD: ${{ inputs.max_threshold }}
        INPUT_ENABLE_FIB: ${{ inputs.enable_fib }}   
