name: Rust CI Input
on:
  push:
  pull_request:

  workflow_dispatch:
    inputs:
    max_threshold:   # id of max_threshold
      description: 'maximum threshold value'
      required: false
      default: 100
    enable_fib:  # id of enable_fib
    description: 'maximum threshold value'
    required: true
    default: true
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.max_threshold }}
      - ${{ inputs.enable_fib }}
