name: Rust CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      enable_fib:
        description: 'Build type (debug or release)'
        required: true
        default: 'true'
        type: boolean
      max_threshold:
       description: 'Build type (debug or release)'
       default: '100'
       type: number

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --${{ github.event.inputs.enable_fib }}  --${{ github.event.inputs.threshold }}
      - run: cargo test --verbose
