name: Cargo Build & Test
on:  
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
  workflow_call:
    inputs:
      enable_fib:
      description: 'enable_fib'
      required: true
      type: boolean
    max_threshold:
    description: 'maxthreshold'
    default: '10'
    required: true
    type: number
    runs: 
    using: 'docker'
    image: 'Dockerfile'
    args:
    - ${{ inputs.enable_fib }}
    - ${{ inputs.max_threshold }}
    
env: 
CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo run --verbose

          
      
    
