name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.TOKEN }}  # Use the TOKEN secret for the username
          password: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN secret for the password

     
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REPOSITORY }}/${{ github.event.repository.name }}:latest
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
