name: ci
on:
  push:
    branches:
      - main
jobs:
   docker-build:
 # Fixed job dependency
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Grant permission to write to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.TOKEN }}  # Use the TOKEN secret for the username
          password: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN secret for the password

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ secrets.TOKEN }}/team_work-lambert_w_function:sha-${{ github.sha }}
            ghcr.io/${{ secrets.TOKEN }}/team_work-lambert_w_function:branch-${{ github.ref_name }}
            ghcr.io/${{ secrets.TOKEN }}/team_work-lambert_w_function:latest

      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
